package player;

public enum RatingsType {
OVERALL, INTERIOR_SHOOTING, MID_SHOOTING, OUTSIDE_SHOOTING, PASSING, HANDLING, STEALING, BLOCKING, INTERIOR_DEFENSE, OUTSIDE_DEFENSE, REBOUNDING, USAGE, INSIDE_T, MID_T, OUTSIDE_T;
}
